import type {
  BaseThemeDefinition,
  BaseThemeId,
  BaseThemeRegistryEntry,
  CustomThemeInputs,
  ResolvedBaseThemeId,
} from "./types";
import { deriveCustomThemeTokens } from "./custom-theme-tokens";

export const PRESET_THEME_INPUTS: Readonly<Record<ResolvedBaseThemeId, CustomThemeInputs>> = {
  obsidian: {
    colorScheme: "dark",
    background: "#09090B",
    surface: "#18181B",
    accent: "#8B5CF6",
    secondaryAccent: "#F59E0B",
  },
  porcelain: {
    colorScheme: "light",
    background: "#F2F3F5",
    surface: "#FCFCFB",
    accent: "#245FA8",
    secondaryAccent: "#2F7C86",
  },
  ocean: {
    colorScheme: "dark",
    background: "#06111F",
    surface: "#0B1B2D",
    accent: "#0EA5E9",
    secondaryAccent: "#14B8A6",
  },
  dusty_rose: {
    colorScheme: "light",
    background: "#EAD9DE",
    surface: "#F4E8EB",
    accent: "#8A405E",
    secondaryAccent: "#B16A80",
  },
  forest: {
    colorScheme: "dark",
    background: "#10231C",
    surface: "#183128",
    accent: "#7FA56F",
    secondaryAccent: "#B1845A",
  },
  lavender: {
    colorScheme: "light",
    background: "#E4DDEF",
    surface: "#F1EDF7",
    accent: "#644A8B",
    secondaryAccent: "#8B70AA",
  },
  polar: {
    colorScheme: "light",
    background: "#DCEBEF",
    surface: "#EEF6F7",
    accent: "#147B8A",
    secondaryAccent: "#506F82",
  },
  sepia: {
    colorScheme: "light",
    background: "#EADFCF",
    surface: "#F5ECDF",
    accent: "#9A4F37",
    secondaryAccent: "#6F543C",
  },
};

export const BASE_THEME_REGISTRY: Readonly<Record<BaseThemeId, BaseThemeRegistryEntry>> = {
  system: {
    id: "system",
    label: "Sistem",
    description: "İşletim sistemi renk tercihine göre Obsidyen veya Porselen tabanını seçer.",
    colorScheme: "system",
  },
  obsidian: {
    id: "obsidian",
    label: "Obsidyen",
    description: "MediaTracker'ın mevcut koyu zinc görünümü.",
    colorScheme: "dark",
    tokens: {
      ...deriveCustomThemeTokens(PRESET_THEME_INPUTS.obsidian),
      background: "#09090b",
      surface1: "#18181b",
      surface2: "#27272a",
      surface3: "#3f3f46",
      elevated: "#18181b",
      textPrimary: "#fafafa",
      textSecondary: "#d4d4d8",
      textMuted: "#71717a",
      border: "#27272a",
      borderStrong: "#3f3f46",
      scrollbarThumbHover: "#52525b",
      shadow: "rgba(0, 0, 0, 0.30)",
      overlay: "rgba(0, 0, 0, 0.72)",
      focus: "#a78bfa",
      accent: "#8b5cf6",
      accentStrong: "#a78bfa",
      accentSoft: "rgba(139, 92, 246, 0.30)",
      accentContrast: "#000000",
      danger: "#fb7185",
      dangerSoft: "rgba(244, 63, 94, 0.12)",
      success: "#34d399",
      successSoft: "rgba(16, 185, 129, 0.12)",
      warning: "#fbbf24",
      warningSoft: "rgba(245, 158, 11, 0.12)",
      inputBackground: "#09090b",
      hover: "#27272a",
      selected: "rgba(139, 92, 246, 0.16)",
    },
  },
  porcelain: {
    id: "porcelain",
    label: "Porselen",
    description: "Nötr porselen yüzeyler ve kontrollü çini mavisi vurgular.",
    colorScheme: "light",
    tokens: {
      ...deriveCustomThemeTokens(PRESET_THEME_INPUTS.porcelain),
      background: "#f2f3f5",
      surface1: "#fcfcfb",
      surface2: "#f6f7f8",
      surface3: "#eef1f4",
      elevated: "#ffffff",
      textPrimary: "#172033",
      textSecondary: "#334155",
      textMuted: "#5c667a",
      border: "#bac4d0",
      borderStrong: "#7c8ea3",
      scrollbarThumbHover: "#60758d",
      shadow: "rgba(23, 32, 51, 0.14)",
      overlay: "rgba(23, 32, 51, 0.48)",
      focus: "#245fa8",
      accent: "#245fa8",
      accentStrong: "#194b88",
      accentSoft: "rgba(36, 95, 168, 0.14)",
      accentContrast: "#ffffff",
      danger: "#a1123f",
      dangerSoft: "rgba(161, 18, 63, 0.10)",
      success: "#08745c",
      successSoft: "rgba(8, 116, 92, 0.10)",
      warning: "#925400",
      warningSoft: "rgba(146, 84, 0, 0.11)",
      inputBackground: "#f8f9fa",
      hover: "#eef2f6",
      selected: "rgba(36, 95, 168, 0.13)",
      secondaryAccent: "#2f7c86",
      disabledText: "#737b87",
      disabledBackground: "#e7e9ec",
      disabledBorder: "#b8c0ca",
      panelBackground: "#fcfcfb", cardBackground: "#f6f7f8", cardHover: "#eef2f5",
      selectedBackground: "#d4e1ed", selectedBorder: "#245fa8", selectedText: "#172033",
      heroBackground: "linear-gradient(135deg, #e5edf5 0%, #f2f3f5 100%)",
    },
  },
  ocean: {
    id: "ocean",
    label: "Okyanus",
    description: "Lacivert yüzeyler üzerinde mavi ve turkuaz vurgular.",
    colorScheme: "dark",
    tokens: {
      ...deriveCustomThemeTokens(PRESET_THEME_INPUTS.ocean),
      background: "#06111f",
      surface1: "#0b1b2d",
      surface2: "#10263d",
      surface3: "#16344f",
      elevated: "#0e2238",
      textPrimary: "#ecfeff",
      textSecondary: "#bae6fd",
      textMuted: "#7dd3fc",
      border: "#164e63",
      borderStrong: "#0e7490",
      scrollbarThumbHover: "#0891b2",
      shadow: "rgba(2, 8, 23, 0.40)",
      overlay: "rgba(2, 8, 23, 0.76)",
      focus: "#22d3ee",
      accent: "#0ea5e9",
      accentStrong: "#22d3ee",
      accentSoft: "rgba(34, 211, 238, 0.16)",
      accentContrast: "#06111f",
      danger: "#fb7185",
      dangerSoft: "rgba(251, 113, 133, 0.12)",
      success: "#2dd4bf",
      successSoft: "rgba(45, 212, 191, 0.12)",
      warning: "#fbbf24",
      warningSoft: "rgba(251, 191, 36, 0.12)",
      inputBackground: "#071827",
      hover: "#10263d",
      selected: "rgba(34, 211, 238, 0.14)",
    },
  },
  dusty_rose: {
    id: "dusty_rose",
    label: "Tozpembe",
    description: "Gül kurusu vurgular, krem yüzeyler ve sakin bordo tonları.",
    colorScheme: "light",
    tokens: {
      ...deriveCustomThemeTokens(PRESET_THEME_INPUTS.dusty_rose),
      background: "#ead9de", surface1: "#f4e8eb", surface2: "#eee0e4",
      surface3: "#e6d4da", elevated: "#faf2f4", textPrimary: "#34242a",
      textSecondary: "#5b414a", textMuted: "#765863", border: "#b8939e",
      borderStrong: "#906070", inputBackground: "#f7edef", hover: "#e8d7dc",
      selected: "rgba(138, 64, 94, 0.14)", focus: "#74324d",
      danger: "#a1123f", success: "#176b55", warning: "#895400",
      disabledText: "#765f67", disabledBackground: "#e2d2d7", disabledBorder: "#ad8d97",
      panelBackground: "#f4e8eb", cardBackground: "#eee0e4", cardHover: "#e8d7dc",
      selectedBackground: "#ead2da", selectedBorder: "#8a405e", selectedText: "#34242a",
      heroBackground: "linear-gradient(135deg, #e4cdd5 0%, #ead9de 100%)",
    },
  },
  forest: {
    id: "forest",
    label: "Orman",
    description: "Çam ve yosun yeşilini sıcak toprak tonlarıyla dengeler.",
    colorScheme: "dark",
    tokens: deriveCustomThemeTokens(PRESET_THEME_INPUTS.forest),
  },
  lavender: {
    id: "lavender",
    label: "Lavanta",
    description: "Soluk lavanta yüzeyleri koyu erik vurgusuyla birleştirir.",
    colorScheme: "light",
    tokens: {
      ...deriveCustomThemeTokens(PRESET_THEME_INPUTS.lavender),
      background: "#e4ddef", surface1: "#f1edf7", surface2: "#ebe5f2",
      surface3: "#e2daeb", elevated: "#f8f5fb", textPrimary: "#2e253b",
      textSecondary: "#514565", textMuted: "#695c7a", border: "#aaa0c2",
      borderStrong: "#766292", inputBackground: "#f5f1f9", hover: "#e4ddec",
      selected: "rgba(100, 74, 139, 0.15)", focus: "#593d80",
      danger: "#a1124f", success: "#176b55", warning: "#845300",
      disabledText: "#6f6579", disabledBackground: "#ddd6e7", disabledBorder: "#a596b6",
      panelBackground: "#f1edf7", cardBackground: "#ebe5f2", cardHover: "#e4ddec",
      selectedBackground: "#ded3ea", selectedBorder: "#644a8b", selectedText: "#2e253b",
      heroBackground: "linear-gradient(135deg, #d9cfe7 0%, #e4ddef 100%)",
    },
  },
  polar: {
    id: "polar",
    label: "Kutup",
    description: "Buz mavisi ve arduvaz tonlarında kontrollü, açık bir tema.",
    colorScheme: "light",
    tokens: {
      ...deriveCustomThemeTokens(PRESET_THEME_INPUTS.polar),
      background: "#dcebef", surface1: "#eef6f7", surface2: "#e7f1f3",
      surface3: "#dbeaec", elevated: "#f7fbfb", textPrimary: "#16313b",
      textSecondary: "#36515c", textMuted: "#526d77", border: "#91b1be",
      borderStrong: "#557f8e", inputBackground: "#f3f8f9", hover: "#dfecef",
      selected: "rgba(20, 123, 138, 0.14)", focus: "#0d6976",
      danger: "#a1123f", success: "#08745c", warning: "#855500",
      disabledText: "#5e727a", disabledBackground: "#d4e3e7", disabledBorder: "#98b4bf",
      panelBackground: "#eef6f7", cardBackground: "#e7f1f3", cardHover: "#dfecef",
      selectedBackground: "#cfe6e9", selectedBorder: "#147b8a", selectedText: "#16313b",
      heroBackground: "linear-gradient(135deg, #cfe3e8 0%, #dcebef 100%)",
    },
  },
  sepia: {
    id: "sepia",
    label: "Sepya",
    description: "Parşömen yüzeyleri, mürekkep kahvesi ve terracotta vurgusu.",
    colorScheme: "light",
    tokens: {
      ...deriveCustomThemeTokens(PRESET_THEME_INPUTS.sepia),
      background: "#eadfcf", surface1: "#f5ecdf", surface2: "#efe4d4", surface3: "#e6d7c3", elevated: "#faf4ea",
      textPrimary: "#35261d", textSecondary: "#594336", textMuted: "#71594a",
      border: "#b89b78", borderStrong: "#795735", inputBackground: "#f8f0e5",
      hover: "#e8dccb", selected: "rgba(154, 79, 55, 0.15)", focus: "#8a432f",
      danger: "#9f2f2f", success: "#42713f", warning: "#875300",
      disabledText: "#716153", disabledBackground: "#ded1bd", disabledBorder: "#aa8f68",
      panelBackground: "#f5ecdf", cardBackground: "#efe4d4", cardHover: "#e8dccb",
      selectedBackground: "#ead2c3", selectedBorder: "#9a4f37", selectedText: "#35261d",
      heroBackground: "linear-gradient(135deg, #dfcfb8 0%, #eadfcf 100%)",
    },
  },
};

export function getBaseThemeDefinition(id: ResolvedBaseThemeId): BaseThemeDefinition {
  return BASE_THEME_REGISTRY[id] as BaseThemeDefinition;
}
