import type {
  BaseThemeDefinition,
  BaseThemeId,
  BaseThemeRegistryEntry,
  CustomThemeInputs,
  ResolvedBaseThemeId,
} from "./types";
import { deriveCustomThemeTokens } from "./custom-theme-tokens";

export const PRESET_THEME_INPUTS: Readonly<Record<ResolvedBaseThemeId, CustomThemeInputs>> = {
  obsidian: {
    colorScheme: "dark",
    background: "#09090B",
    surface: "#18181B",
    accent: "#8B5CF6",
    secondaryAccent: "#F59E0B",
  },
  porcelain: {
    colorScheme: "light",
    background: "#F5F5F4",
    surface: "#FAFAF9",
    accent: "#7C3AED",
    secondaryAccent: "#B45309",
  },
  ocean: {
    colorScheme: "dark",
    background: "#06111F",
    surface: "#0B1B2D",
    accent: "#0EA5E9",
    secondaryAccent: "#14B8A6",
  },
  dusty_rose: {
    colorScheme: "light",
    background: "#F5ECEE",
    surface: "#FFF8F6",
    accent: "#8A3F5D",
    secondaryAccent: "#B66A7C",
  },
  forest: {
    colorScheme: "dark",
    background: "#10231C",
    surface: "#183128",
    accent: "#7FA56F",
    secondaryAccent: "#B1845A",
  },
  lavender: {
    colorScheme: "light",
    background: "#F1EFF8",
    surface: "#FAF8FF",
    accent: "#66528F",
    secondaryAccent: "#9B79B0",
  },
  polar: {
    colorScheme: "light",
    background: "#EEF5F7",
    surface: "#F8FBFC",
    accent: "#137C8B",
    secondaryAccent: "#4A6A7E",
  },
  sepia: {
    colorScheme: "light",
    background: "#F2E6CF",
    surface: "#FBF2E2",
    accent: "#9A4F37",
    secondaryAccent: "#6F543C",
  },
};

export const BASE_THEME_REGISTRY: Readonly<Record<BaseThemeId, BaseThemeRegistryEntry>> = {
  system: {
    id: "system",
    label: "Sistem",
    description: "İşletim sistemi renk tercihine göre Obsidyen veya Porselen tabanını seçer.",
    colorScheme: "system",
  },
  obsidian: {
    id: "obsidian",
    label: "Obsidyen",
    description: "MediaTracker'ın mevcut koyu zinc görünümü.",
    colorScheme: "dark",
    tokens: {
      ...deriveCustomThemeTokens(PRESET_THEME_INPUTS.obsidian),
      background: "#09090b",
      surface1: "#18181b",
      surface2: "#27272a",
      surface3: "#3f3f46",
      elevated: "#18181b",
      textPrimary: "#fafafa",
      textSecondary: "#d4d4d8",
      textMuted: "#71717a",
      border: "#27272a",
      borderStrong: "#3f3f46",
      scrollbarThumbHover: "#52525b",
      shadow: "rgba(0, 0, 0, 0.30)",
      overlay: "rgba(0, 0, 0, 0.72)",
      focus: "#a78bfa",
      accent: "#8b5cf6",
      accentStrong: "#a78bfa",
      accentSoft: "rgba(139, 92, 246, 0.30)",
      accentContrast: "#fafafa",
      danger: "#fb7185",
      dangerSoft: "rgba(244, 63, 94, 0.12)",
      success: "#34d399",
      successSoft: "rgba(16, 185, 129, 0.12)",
      warning: "#fbbf24",
      warningSoft: "rgba(245, 158, 11, 0.12)",
      inputBackground: "#09090b",
      hover: "#27272a",
      selected: "rgba(139, 92, 246, 0.16)",
    },
  },
  porcelain: {
    id: "porcelain",
    label: "Porselen",
    description: "Kırık beyaz, açık stone ve yumuşak gri temeli.",
    colorScheme: "light",
    tokens: {
      ...deriveCustomThemeTokens(PRESET_THEME_INPUTS.porcelain),
      background: "#f5f5f4",
      surface1: "#fafaf9",
      surface2: "#e7e5e4",
      surface3: "#d6d3d1",
      elevated: "#fffdfa",
      textPrimary: "#1c1917",
      textSecondary: "#44403c",
      textMuted: "#78716c",
      border: "#d6d3d1",
      borderStrong: "#a8a29e",
      scrollbarThumbHover: "#78716c",
      shadow: "rgba(28, 25, 23, 0.14)",
      overlay: "rgba(28, 25, 23, 0.48)",
      focus: "#7c3aed",
      accent: "#7c3aed",
      accentStrong: "#6d28d9",
      accentSoft: "rgba(124, 58, 237, 0.14)",
      accentContrast: "#fafaf9",
      danger: "#be123c",
      dangerSoft: "rgba(190, 18, 60, 0.10)",
      success: "#047857",
      successSoft: "rgba(4, 120, 87, 0.10)",
      warning: "#b45309",
      warningSoft: "rgba(180, 83, 9, 0.10)",
      inputBackground: "#fafaf9",
      hover: "#e7e5e4",
      selected: "rgba(124, 58, 237, 0.12)",
    },
  },
  ocean: {
    id: "ocean",
    label: "Okyanus",
    description: "Lacivert yüzeyler üzerinde mavi ve turkuaz vurgular.",
    colorScheme: "dark",
    tokens: {
      ...deriveCustomThemeTokens(PRESET_THEME_INPUTS.ocean),
      background: "#06111f",
      surface1: "#0b1b2d",
      surface2: "#10263d",
      surface3: "#16344f",
      elevated: "#0e2238",
      textPrimary: "#ecfeff",
      textSecondary: "#bae6fd",
      textMuted: "#7dd3fc",
      border: "#164e63",
      borderStrong: "#0e7490",
      scrollbarThumbHover: "#0891b2",
      shadow: "rgba(2, 8, 23, 0.40)",
      overlay: "rgba(2, 8, 23, 0.76)",
      focus: "#22d3ee",
      accent: "#0ea5e9",
      accentStrong: "#22d3ee",
      accentSoft: "rgba(34, 211, 238, 0.16)",
      accentContrast: "#06111f",
      danger: "#fb7185",
      dangerSoft: "rgba(251, 113, 133, 0.12)",
      success: "#2dd4bf",
      successSoft: "rgba(45, 212, 191, 0.12)",
      warning: "#fbbf24",
      warningSoft: "rgba(251, 191, 36, 0.12)",
      inputBackground: "#071827",
      hover: "#10263d",
      selected: "rgba(34, 211, 238, 0.14)",
    },
  },
  dusty_rose: {
    id: "dusty_rose",
    label: "Tozpembe",
    description: "Gül kurusu vurgular, krem yüzeyler ve sakin bordo tonları.",
    colorScheme: "light",
    tokens: deriveCustomThemeTokens(PRESET_THEME_INPUTS.dusty_rose),
  },
  forest: {
    id: "forest",
    label: "Orman",
    description: "Çam ve yosun yeşilini sıcak toprak tonlarıyla dengeler.",
    colorScheme: "dark",
    tokens: deriveCustomThemeTokens(PRESET_THEME_INPUTS.forest),
  },
  lavender: {
    id: "lavender",
    label: "Lavanta",
    description: "Soluk lavanta yüzeyleri koyu erik vurgusuyla birleştirir.",
    colorScheme: "light",
    tokens: deriveCustomThemeTokens(PRESET_THEME_INPUTS.lavender),
  },
  polar: {
    id: "polar",
    label: "Kutup",
    description: "Buz mavisi ve slate tonlarında kontrollü, açık bir tema.",
    colorScheme: "light",
    tokens: deriveCustomThemeTokens(PRESET_THEME_INPUTS.polar),
  },
  sepia: {
    id: "sepia",
    label: "Sepya",
    description: "Parşömen yüzeyleri, mürekkep kahvesi ve terracotta vurgusu.",
    colorScheme: "light",
    tokens: deriveCustomThemeTokens(PRESET_THEME_INPUTS.sepia),
  },
};

export function getBaseThemeDefinition(id: ResolvedBaseThemeId): BaseThemeDefinition {
  return BASE_THEME_REGISTRY[id] as BaseThemeDefinition;
}
