import { describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));

import { decodeGroundedExtractionRequest } from "@/features/recommendations/research/extraction/domain/codec";
import { buildGroundedEvidenceUnits } from "@/features/recommendations/research/extraction/domain/evidence-units";
import { decodeGroundedExtractionModelOutput, validateGroundedExtractionGrounding } from "@/features/recommendations/research/extraction/domain/model-output";
import { buildMinimizedGroundedModelInput } from "@/features/recommendations/research/extraction/prompt/input-builder";
import { createGroundedExtractionRequest } from "@/features/recommendations/research/testing/extraction-fixtures";

describe("D7-R3B extraction request and minimized model input", () => {
  it("strict request, packet hash ve registry aspect definition doğrular", async () => { expect((await decodeGroundedExtractionRequest(await createGroundedExtractionRequest())).ok).toBe(true); });
  it.each(["ownerId", "userId", "rating", "note", "progress", "rawPrompt", "searchQuery", "providerResponse", "unexpected"])("%s alanını fail-closed reddeder", async (field) => { const request = { ...(await createGroundedExtractionRequest()), [field]: "forbidden" }; expect((await decodeGroundedExtractionRequest(request)).ok).toBe(false); });
  it("packet hash veya aspect definition drift'ini reddeder", async () => { const request = await createGroundedExtractionRequest(); expect((await decodeGroundedExtractionRequest({ ...request, packet: { ...request.packet, packetContentHash: `sha256:${"0".repeat(64)}` } })).ok).toBe(false); expect((await decodeGroundedExtractionRequest({ ...request, aspectDefinition: { ...request.aspectDefinition, labelEn: "Changed" } })).ok).toBe(false); });
  it("model input'tan title/provider/QID/URL/role/minimum ve personal alanları çıkarır", async () => { const request = await createGroundedExtractionRequest(); const units = await buildGroundedEvidenceUnits({ packet: request.packet, maxUnits: 64 }); const model = buildMinimizedGroundedModelInput({ request, units: units.eligibleUnits }); const json = JSON.stringify(model); expect(model.candidateRef).toBe("candidate-1"); expect(json).not.toContain("Private fixture title"); expect(json).not.toContain("anilist"); expect(json).not.toContain("Q123"); expect(json).not.toContain("wikipedia.org"); expect(model).not.toHaveProperty("role"); expect(model).not.toHaveProperty("minimumLevel"); expect(model).not.toHaveProperty("candidateIdentity"); });
});

describe("D7-R3B evidence units", () => {
  it("stable, bounded ve citation-linked units üretir", async () => { const request = await createGroundedExtractionRequest(); const first = await buildGroundedEvidenceUnits({ packet: request.packet, maxUnits: 64 }); const second = await buildGroundedEvidenceUnits({ packet: request.packet, maxUnits: 64 }); expect(first.units).toEqual(second.units); expect(first.units.length).toBeGreaterThan(0); expect(first.units.every((unit) => unit.text.length <= 700 && unit.retention === "transient_only" && unit.citationId)).toBe(true); });
  it("64 unit hard cap uygular", async () => { const request = await createGroundedExtractionRequest(); const units = await buildGroundedEvidenceUnits({ packet: request.packet, maxUnits: 1 }); expect(units.units).toHaveLength(1); });
  it("security-flagged unit'i model inputundan dışlar", async () => { const request = await createGroundedExtractionRequest(); const passage = request.packet.passages[0]; const packet = { ...request.packet, passages: [{ ...passage, securityFlags: ["prompt_injection_pattern" as const] }] }; const units = await buildGroundedEvidenceUnits({ packet, maxUnits: 64 }); expect(units.units.length).toBeGreaterThan(0); expect(units.eligibleUnits).toHaveLength(0); expect(units.excludedUnitIds).toHaveLength(units.units.length); });
});

describe("D7-R3B strict model output and all-or-nothing grounding", () => {
  async function context() { const request = await createGroundedExtractionRequest(); const built = await buildGroundedEvidenceUnits({ packet: request.packet, maxUnits: 64 }); const unit = built.eligibleUnits[0]; return { request, built, unit, valid: { version: 1, assessments: [{ passageId: unit.passageId, finding: "supports_presence", level: "significant", confidence: "high", evidenceUnitIds: [unit.unitId], basis: "affects_character_decisions" }] } }; }
  it("support/absence/irrelevant/insufficient kombinasyonlarını strict çözer", async () => { const { valid } = await context(); expect(decodeGroundedExtractionModelOutput(valid, 8).ok).toBe(true); for (const assessment of [{ ...valid.assessments[0], finding: "supports_explicit_absence", level: null, basis: "explicit_absence_statement" }, { ...valid.assessments[0], finding: "irrelevant", level: null, evidenceUnitIds: [], basis: "unrelated_context" }, { ...valid.assessments[0], finding: "insufficient", level: null, evidenceUnitIds: [], basis: "context_insufficient" }]) expect(decodeGroundedExtractionModelOutput({ version: 1, assessments: [assessment] }, 8).ok).toBe(true); });
  it.each(["claim", "url", "reason"])("free-form %s alanını reddeder", async (field) => { const { valid } = await context(); expect(decodeGroundedExtractionModelOutput({ version: 1, assessments: [{ ...valid.assessments[0], [field]: "x" }] }, 8).ok).toBe(false); });
  it("invalid level/basis, duplicate passage ve assessment budget'ını reddeder", async () => { const { valid } = await context(); expect(decodeGroundedExtractionModelOutput({ version: 1, assessments: [{ ...valid.assessments[0], level: null }] }, 8).ok).toBe(false); expect(decodeGroundedExtractionModelOutput({ version: 1, assessments: [valid.assessments[0], valid.assessments[0]] }, 8).ok).toBe(false); expect(decodeGroundedExtractionModelOutput({ version: 1, assessments: Array(9).fill(valid.assessments[0]) }, 8).ok).toBe(false); });
  it("unknown/wrong/excluded unit için bütün output'u reddeder", async () => { const { request, built, unit, valid } = await context(); const decoded = decodeGroundedExtractionModelOutput(valid, 8); if (!decoded.ok) throw new Error("fixture_invalid"); expect(validateGroundedExtractionGrounding({ output: decoded.value, packet: request.packet, units: built.units }).ok).toBe(true); const unknown = { ...decoded.value, assessments: [{ ...decoded.value.assessments[0], evidenceUnitIds: [`sha256:${"f".repeat(64)}`] }] }; expect(validateGroundedExtractionGrounding({ output: unknown, packet: request.packet, units: built.units }).ok).toBe(false); expect(validateGroundedExtractionGrounding({ output: decoded.value, packet: request.packet, units: built.units, excludedUnitIds: [unit.unitId] }).ok).toBe(false); });
});

