import { describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { buildGroundedEvidenceUnits } from "@/features/recommendations/research/extraction/domain/evidence-units";
import { buildDeterministicGroundedClaims } from "@/features/recommendations/research/extraction/domain/claims";
import { buildDeterministicResearchDecision } from "@/features/recommendations/research/extraction/domain/decision";
import { validateGroundedExtractionGrounding } from "@/features/recommendations/research/extraction/domain/model-output";
import { createGroundedExtractionPacket, createGroundedExtractionRequest, SYNTHETIC_EXPLICIT_ABSENCE, SYNTHETIC_NO_ROMANCE } from "@/features/recommendations/research/testing/extraction-fixtures";

async function fixture(text?: string) { const request = await createGroundedExtractionRequest(text ? { packet: await createGroundedExtractionPacket({ text }) } : {}); const units = await buildGroundedEvidenceUnits({ packet: request.packet, maxUnits: 64 }); return { request, units, unit: units.eligibleUnits[0] }; }
describe("D7-R3B deterministic claims and decisions", () => {
  it("Steins;Gate-like significant support'u citation-bound medium-cap claim/decision yapar", async () => { const { request, units, unit } = await fixture(); const output = { version: 1 as const, assessments: [{ passageId: unit.passageId, finding: "supports_presence" as const, level: "significant" as const, confidence: "high" as const, evidenceUnitIds: [unit.unitId], basis: "affects_character_decisions" as const }] }; expect(validateGroundedExtractionGrounding({ output, packet: request.packet, units: units.units }).ok).toBe(true); const claims = await buildDeterministicGroundedClaims({ request, output, units: units.eligibleUnits }); expect(claims).toHaveLength(1); expect(claims[0].confidence).toBe("medium"); expect(claims[0].paraphrasedClaim).not.toContain(unit.text); const decision = buildDeterministicResearchDecision({ request, claims, now: () => new Date("2026-08-09T00:00:00Z") }); expect(decision.status).toBe("supported"); expect(decision.level).toBe("significant"); expect(decision.confidence).toBe("medium"); expect(decision.independentSourceCount).toBe(1); });
  it("passage dışı memory claim veya Kakegurui-like omission'dan support üretmez", async () => { const { request, units, unit } = await fixture(SYNTHETIC_NO_ROMANCE); const hallucinated = { version: 1 as const, assessments: [{ passageId: unit.passageId, finding: "supports_presence" as const, level: "significant" as const, confidence: "high" as const, evidenceUnitIds: [`sha256:${"e".repeat(64)}`], basis: "affects_plot" as const }] }; expect(validateGroundedExtractionGrounding({ output: hallucinated, packet: request.packet, units: units.units }).ok).toBe(false); const decision = buildDeterministicResearchDecision({ request, claims: [] }); expect(decision.status).toBe("unknown"); expect(decision.reasonCode).toBe("passage_insufficient"); });
  it("explicit absence'ı contradict claim yapar; omission yapmaz", async () => { const { request, units, unit } = await fixture(SYNTHETIC_EXPLICIT_ABSENCE); const output = { version: 1 as const, assessments: [{ passageId: unit.passageId, finding: "supports_explicit_absence" as const, level: null, confidence: "medium" as const, evidenceUnitIds: [unit.unitId], basis: "explicit_absence_statement" as const }] }; const claims = await buildDeterministicGroundedClaims({ request, output, units: units.eligibleUnits }); expect(claims[0].polarity).toBe("contradict"); const decision = buildDeterministicResearchDecision({ request, claims }); expect(decision.status).toBe("contradicted"); expect(decision.level).toBeNull(); });
  it("support + explicit absence çelişkisini unknown/conflicting_sources tutar", async () => { const { request, units, unit } = await fixture(); const support = { version: 1 as const, assessments: [{ passageId: unit.passageId, finding: "supports_presence" as const, level: "significant" as const, confidence: "medium" as const, evidenceUnitIds: [unit.unitId], basis: "affects_plot" as const }] }; const supportClaims = await buildDeterministicGroundedClaims({ request, output: support, units: units.eligibleUnits }); const contradict = { ...support, assessments: [{ ...support.assessments[0], finding: "supports_explicit_absence" as const, level: null, basis: "explicit_absence_statement" as const }] }; const contradictClaims = await buildDeterministicGroundedClaims({ request, output: contradict, units: units.eligibleUnits }); const decision = buildDeterministicResearchDecision({ request, claims: [...supportClaims, ...contradictClaims] }); expect(decision.status).toBe("unknown"); expect(decision.reasonCode).toBe("conflicting_sources"); expect(decision.independentSourceCount).toBe(1); });
  it("tek low-confidence primary'yi strong primary decision yapmaz", async () => { const { request, units, unit } = await fixture(); const output = { version: 1 as const, assessments: [{ passageId: unit.passageId, finding: "supports_presence" as const, level: "primary" as const, confidence: "low" as const, evidenceUnitIds: [unit.unitId], basis: "core_premise" as const }] }; const claims = await buildDeterministicGroundedClaims({ request, output, units: units.eligibleUnits }); expect(buildDeterministicResearchDecision({ request, claims }).level).toBe("significant"); });
  it("decision exact version scope'u korur", async () => { const { request } = await fixture(); const decision = buildDeterministicResearchDecision({ request, claims: [] }); expect(decision.versionScope.scopeKey).toBe(request.packet.versionScope.scopeKey); });
});
