import { describe,expect,it,vi } from "vitest";
import { cacheSocialActivityPreferences,enqueueSocialOutbox,findMatchingLocalMedia,flushSocialOutbox,loadRecommendationLinks,loadSocialOutbox,queueMediaSocialEvents,recommendationToPlanningMedia,saveRecommendationLink,SOCIAL_OUTBOX_KEY,type StorageLike,validRecommendationLinkIds } from "@/lib/social/local-social";
import { DEFAULT_ACTIVITY_PREFERENCES,mediaToSocialSnapshot } from "@/lib/social/interactions";
import type { MediaItem } from "@/lib/types";

function storage(initial:Record<string,string>={}):StorageLike&{data:Record<string,string>}{const data={...initial};return{data,getItem:(key)=>data[key]??null,setItem:(key,value)=>{data[key]=value;}};}
const media:MediaItem={id:"m1",title:"Dune",type:"book",status:"planning",coverImage:"",currentProgress:0,totalProgress:500,externalSource:"openlibrary",externalId:"/works/OL1W"};

describe("social local-first stores",()=>{
  it("falls back safely for corrupt outbox data",()=>expect(loadSocialOutbox(storage({[SOCIAL_OUTBOX_KEY]:"{"}))).toEqual([]));
  it("does not queue without a signed-in social profile cache",()=>expect(queueMediaSocialEvents(media,{...media,status:"reading"},null,storage())).toEqual([]));
  it("does not queue when the social profile is not configured",()=>{const store=storage();cacheSocialActivityPreferences("u",false,DEFAULT_ACTIVITY_PREFERENCES,store);expect(queueMediaSocialEvents(media,{...media,status:"completed"},"u",store)).toEqual([]);});
  it("queues a preferred completed event with a stable user id",()=>{const store=storage();cacheSocialActivityPreferences("u",true,DEFAULT_ACTIVITY_PREFERENCES,store);const queued=queueMediaSocialEvents({...media,status:"reading"},{...media,status:"completed"},"u",store);expect(queued).toHaveLength(1);expect(queued[0]).toMatchObject({type:"activity_publish",userId:"u",retryCount:0,payload:{eventType:"media_completed"}});});
  it("coalesces the same idempotency key",()=>{const store=storage();const item={id:"1",type:"activity_publish" as const,userId:"u",idempotencyKey:"same-key",payload:{eventType:"media_completed" as const,visibility:"followers" as const,media:mediaToSocialSnapshot(media),sourceEventId:"m1:complete",dedupeKey:"same-key"},createdAt:new Date().toISOString(),retryCount:0};enqueueSocialOutbox(item,store);enqueueSocialOutbox({...item,id:"2"},store);expect(loadSocialOutbox(store)).toHaveLength(1);expect(loadSocialOutbox(store)[0].id).toBe("2");});
  it("removes successful events and retains failed events with retry metadata",async()=>{const store=storage();cacheSocialActivityPreferences("u",true,DEFAULT_ACTIVITY_PREFERENCES,store);queueMediaSocialEvents({...media,status:"reading"},{...media,status:"completed"},"u",store);const send=vi.fn().mockRejectedValue(new Error("offline"));const remaining=await flushSocialOutbox("u",send,store);expect(remaining[0]).toMatchObject({retryCount:1,lastError:"offline"});await flushSocialOutbox("u",vi.fn().mockResolvedValue(undefined),store);expect(loadSocialOutbox(store)).toEqual([]);});
  it("never flushes another user's events",async()=>{const store=storage();cacheSocialActivityPreferences("other",true,DEFAULT_ACTIVITY_PREFERENCES,store);queueMediaSocialEvents({...media,status:"reading"},{...media,status:"completed"},"other",store);const send=vi.fn();await flushSocialOutbox("current",send,store);expect(send).not.toHaveBeenCalled();expect(loadSocialOutbox(store)).toHaveLength(1);});
  it("keeps recommendation links isolated by user",()=>{const store=storage();saveRecommendationLink({recommendationId:"r1",localMediaId:"m1",canonicalMediaKey:"k",linkedAt:new Date().toISOString(),userId:"a"},store);saveRecommendationLink({recommendationId:"r2",localMediaId:"m2",canonicalMediaKey:"k2",linkedAt:new Date().toISOString(),userId:"b"},store);expect(loadRecommendationLinks("a",store).map((item)=>item.recommendationId)).toEqual(["r1"]);});
  it("keeps one local link per recommendation on a device",()=>{const store=storage();const base={recommendationId:"r1",canonicalMediaKey:"k",linkedAt:new Date().toISOString(),userId:"a"};saveRecommendationLink({...base,localMediaId:"m1"},store);saveRecommendationLink({...base,localMediaId:"m2"},store);expect(loadRecommendationLinks("a",store)).toHaveLength(1);expect(loadRecommendationLinks("a",store)[0].localMediaId).toBe("m2");});
  it("offers device linking again when another device has no local link",()=>expect(validRecommendationLinkIds("a",[media],storage())).toEqual([]));
  it("keeps the cloud-independent link record but treats deleted local media as unlinked",()=>{const store=storage();saveRecommendationLink({recommendationId:"r1",localMediaId:media.id,canonicalMediaKey:"k",linkedAt:new Date().toISOString(),userId:"a"},store);expect(validRecommendationLinkIds("a",[media],store)).toEqual(["r1"]);expect(validRecommendationLinkIds("a",[],store)).toEqual([]);expect(loadRecommendationLinks("a",store)).toHaveLength(1);});
  it("matches existing media by canonical source/id without duplicates",()=>expect(findMatchingLocalMedia(mediaToSocialSnapshot(media),[media])?.id).toBe("m1"));
  it("creates a planning item without social fields",()=>{const item=recommendationToPlanningMedia("r1",mediaToSocialSnapshot(media));expect(item).toMatchObject({id:"social-r1",status:"planning",currentProgress:0});expect(item).not.toHaveProperty("recommendationId");});
});
