import { describe, expect, it, vi } from "vitest";
import { enqueueXpOutbox, flushXpOutbox, loadXpOutbox, queueXpMediaState, XP_OUTBOX_KEY, type XpOutboxItem, type XpStorageLike } from "@/lib/xp/outbox";
import type { MediaItem } from "@/lib/types";

function storage(initial: Record<string,string> = {}): XpStorageLike & { data: Record<string,string> } { const data={...initial}; return {data,getItem:(key)=>data[key]??null,setItem:(key,value)=>{data[key]=value;}}; }
const planning:MediaItem={id:"m1",title:"Dune",type:"book",status:"planning",coverImage:"",currentProgress:0,totalProgress:500,userRating:null,personalNotes:"private"};

describe("XP desired-state outbox",()=>{
  it("uses the stable storage key and corrupt data falls back safely",()=>{expect(XP_OUTBOX_KEY).toBe("media-tracker-xp-outbox");expect(loadXpOutbox(storage({[XP_OUTBOX_KEY]:"{"}))).toEqual([]);});
  it("stores a safe current state without amount, full media, private note or data URL",()=>{const store=storage();const item=queueXpMediaState({...planning,coverImage:"data:image/png;base64,secret"},"u",false,store);expect(item?.safeMediaState).toMatchObject({status:"planning",progress:0,totalProgress:500,hasRating:false,deleted:false});expect(item).not.toHaveProperty("amount");expect(JSON.stringify(item)).not.toContain("private");expect(JSON.stringify(item)).not.toContain("data:image");});
  it("coalesces by user and canonical media so the latest state wins",()=>{const store=storage();const first=queueXpMediaState(planning,"u",false,store);const latest=queueXpMediaState({...planning,status:"completed",currentProgress:500},"u",false,store);expect(first).not.toBeNull();expect(loadXpOutbox(store)).toHaveLength(1);expect(loadXpOutbox(store)[0]).toMatchObject({id:latest?.id,deleted:false,safeMediaState:{status:"completed"}});});
  it("keeps an offline delete tombstone",()=>{const store=storage();queueXpMediaState(planning,"u",true,store);expect(loadXpOutbox(store)[0]).toMatchObject({deleted:true,safeMediaState:{deleted:true}});});
  it("delete followed by re-add compacts to the final live state",()=>{const store=storage();queueXpMediaState(planning,"u",true,store);queueXpMediaState({...planning,status:"reading"},"u",false,store);expect(loadXpOutbox(store)).toHaveLength(1);expect(loadXpOutbox(store)[0]).toMatchObject({deleted:false,safeMediaState:{status:"reading",deleted:false}});});
  it("repeated identical state remains one pending reconciliation",()=>{const store=storage();queueXpMediaState(planning,"u",false,store);queueXpMediaState(planning,"u",false,store);expect(loadXpOutbox(store)).toHaveLength(1);});
  it("flushes the current user's states in one batch",async()=>{const store=storage();queueXpMediaState(planning,"u",false,store);queueXpMediaState({...planning,id:"m2",externalId:"m2",title:"Foundation"},"u",false,store);const send=vi.fn<(items:XpOutboxItem[])=>Promise<void>>().mockResolvedValue(undefined);await flushXpOutbox("u",send,store);expect(send).toHaveBeenCalledTimes(1);expect(send.mock.calls[0][0]).toHaveLength(2);expect(loadXpOutbox(store)).toEqual([]);});
  it("retains a failed batch with retry metadata",async()=>{const store=storage();queueXpMediaState(planning,"u",false,store);const remaining=await flushXpOutbox("u",vi.fn().mockRejectedValue(new Error("offline")),store);expect(remaining[0]).toMatchObject({retryCount:1,lastError:"offline"});});
  it("does not discard a newer state queued while an older batch is in flight",async()=>{const store=storage();queueXpMediaState(planning,"u",false,store);await flushXpOutbox("u",async()=>{queueXpMediaState({...planning,status:"completed",currentProgress:500},"u",false,store);},store);expect(loadXpOutbox(store)).toHaveLength(1);expect(loadXpOutbox(store)[0].safeMediaState.status).toBe("completed");});
  it("never flushes another user's item",async()=>{const store=storage();const item=queueXpMediaState(planning,"other",false,store);const send=vi.fn<(items:XpOutboxItem[])=>Promise<void>>();await flushXpOutbox("current",send,store);expect(send).not.toHaveBeenCalled();expect(loadXpOutbox(store)).toEqual(item?[item]:[]);});
  it("does not impose an XP reward cap on a normal 50-item batch",async()=>{const store=storage();for(let index=0;index<50;index+=1)queueXpMediaState({...planning,id:`m${index}`,externalId:`m${index}`,title:`Media ${index}`,status:"completed"},"u",false,store);const send=vi.fn<(items:XpOutboxItem[])=>Promise<void>>().mockResolvedValue(undefined);await flushXpOutbox("u",send,store);expect(send.mock.calls[0][0]).toHaveLength(50);});
  it("replaces an explicitly enqueued state for the same logical media",()=>{const store=storage();const first=queueXpMediaState(planning,"u",false,store);expect(first).not.toBeNull();if(!first)return;enqueueXpOutbox({...first,id:"new",updatedAt:new Date().toISOString()},store);expect(loadXpOutbox(store)).toHaveLength(1);expect(loadXpOutbox(store)[0].id).toBe("new");});
});
