import { readFileSync, readdirSync } from "node:fs";
import { describe, expect, it } from "vitest";

const migrationName="20260721143000_xp_reversible_local_state.sql";
const sql=readFileSync(new URL(`../supabase/migrations/${migrationName}`,import.meta.url),"utf8").trim();
const schema=readFileSync(new URL("../supabase/schema.sql",import.meta.url),"utf8");
const begin="-- BEGIN XP REVERSIBLE LOCAL STATE";const end="-- END XP REVERSIBLE LOCAL STATE";
const schemaBlock=schema.slice(schema.lastIndexOf(begin),schema.lastIndexOf(end)+end.length).trim();

function functionBody(name:string):string { const start=sql.lastIndexOf(`create or replace function public.${name}`);expect(start).toBeGreaterThan(-1);const tail=sql.slice(start);const finish=tail.indexOf("\n$$;");expect(finish).toBeGreaterThan(-1);return tail.slice(0,finish+4); }

describe("XP reversible local-state SQL contract (static, not live PostgreSQL/RLS)",()=>{
  it("uses a unique 14-digit migration and leaves the applied XP V2 migration present",()=>{expect(migrationName).toMatch(/^\d{14}_.+\.sql$/);const names=readdirSync(new URL("../supabase/migrations/",import.meta.url));expect(new Set(names.map((name)=>name.slice(0,14))).size).toBe(names.length);expect(names).toContain("20260721140000_xp_v2_progression.sql");});
  it("creates the single-active-entitlement and one-time conversion read models with RLS",()=>{for(const table of ["xp_media_entitlements","xp_local_state_conversions"]){expect(sql).toContain(`create table if not exists public.${table}`);expect(sql).toContain(`alter table public.${table} enable row level security`);}expect(sql).toContain("primary key (user_id,canonical_media_key,entitlement_type)");expect(sql).toContain("revoke insert,update,delete on public.xp_media_entitlements,public.xp_local_state_conversions from anon,authenticated");});
  it("keeps allocations positive while applying server-controlled grant, revoke and restore effects",()=>{expect(sql).toContain("event_action text not null default 'grant'");expect(sql).toContain("effect smallint not null default 1");expect(sql).toContain("event_action in ('grant','revoke','restore')");expect(sql).toContain("if v_amount<=0 then raise exception 'invalid_xp_allocation'");expect(sql).toContain("p_action='revoke' then -v_amount else v_amount");expect(sql).not.toMatch(/xp_sync_media_states\([^)]*(amount|effect)/i);});
  it("reconciles started, completed, rating, review and showcase eligibility from current state",()=>{const body=functionBody("xp_reconcile_media_state");for(const type of ["media_started","media_completed","media_rated","review_published","showcase_curated"])expect(body).toContain(`'${type}'`);expect(body).toContain("v_status in ('watching','reading','completed') or v_progress>0");expect(body).toContain("v_status='completed'");expect(body).toContain("profile_media_showcase");expect(body).toContain("profile_shared_notes");});
  it("writes distinct grant/revoke/restore ledger entries and repeated desired state is a no-op",()=>{const body=functionBody("xp_reconcile_entitlement");expect(body).toContain("v_action:='grant'");expect(body).toContain("'revoke'");expect(body).toContain("'restore'");expect(body).toContain("return jsonb_build_object('changed',false)");expect(body).toContain("pg_advisory_xact_lock");});
  it("supports delete tombstones, replace reconciliation and batches up to 1000 without a reward cap",()=>{const body=functionBody("xp_sync_media_states");expect(body).toContain("jsonb_array_length(p_items)>1000");expect(body).toContain("if p_replace then");expect(body).toContain("'deleted',true");expect(body).not.toContain("daily_limit");expect(body).not.toContain("date_trunc('day'");});
  it("removes product daily quotas from local, recommendation and feedback effective functions",()=>{expect(functionBody("xp_attest_local_event")).toContain("xp_state_sync_required");for(const name of ["xp_award_recommendation_completion","xp_recommendation_feedback_trigger"]){const body=functionBody(name);expect(body).not.toContain("date_trunc('day'");expect(body).not.toMatch(/v_count\s*<\s*5/);}expect(sql).toContain("No product-level daily XP quota remains");});
  it("converts only historical local/legacy allocations once without deleting immutable history",()=>{const body=functionBody("xp_convert_legacy_local_state");expect(body).toContain("e.trust_level='legacy_attested'");expect(body).toContain("e.source_type<>'media_state'");expect(body).toContain("'reversal'");expect(body).toContain("'revoke'");expect(body).toContain("xp_local_state_conversions");expect(body).not.toMatch(/delete\s+from\s+public\.xp_events/i);});
  it("requires a full first reconciliation only when historical XP needs conversion",()=>{const body=functionBody("xp_sync_media_states");expect(body).toContain("not p_replace");expect(body).toContain("library_full_sync_required");expect(body).toContain("xp_local_state_conversions");});
  it("keeps social and quest awards permanent and idempotent",()=>{expect(functionBody("xp_award_recommendation_completion")).toContain("recommendation_completed_recipient:");expect(functionBody("xp_award_recommendation_completion")).toContain("recommendation_completed_sender:");const quests=functionBody("xp_evaluate_quests");expect(quests).toContain("coalesce(public.xp_user_quest_progress.completed_at,excluded.completed_at)");expect(quests).toContain("on conflict(user_id,badge_key) do nothing");});
  it("repairs an unearned world title after a negative adjustment without deleting badges",()=>{const body=functionBody("xp_repair_selected_title");expect(body).toContain("v_known_world_title");expect(body).toContain("update public.profiles set selected_title=v_fallback");expect(body).not.toContain("xp_user_badges");});
  it("returns signed event history and an explainable source breakdown",()=>{const body=functionBody("get_xp_dashboard");for(const key of ["action","effect","localCurrentXp","socialXp","systemXp","legacyCorrectionXp","librarySynchronized"])expect(body).toContain(`'${key}'`);});
  it("keeps schema.sql synchronized with the new migration",()=>expect(schemaBlock).toBe(sql));
});
