// Existing internal diagnostic vocabulary only; upstream/free-text failures are opaque.
const CODES = new Set([
  "content_type_rejected",
  "dns_lookup_failed",
  "dns_result_empty",
  "dns_security_rejected",
  "grounded_decision_validation_failed",
  "http_failed",
  "invalid_encoding",
  "invalid_request",
  "redirect_rejected",
  "research_budget_invalid",
  "research_discovery_query_too_long",
  "research_document_empty_after_normalization",
  "research_document_oversized_after_normalization",
  "research_document_security_rejected",
  "research_handoff_scope_invalid",
  "research_scope_edition_fields_invalid",
  "research_scope_edition_identity_unverified",
  "research_scope_exact_identity_invalid",
  "research_scope_installment_fields_invalid",
  "research_scope_parent_relation_unavailable",
  "research_scope_season_fields_invalid",
  "research_scope_work_fields_forbidden",
  "research_shadow_aborted",
  "security_rejected",
  "wikidata_bindings_missing",
  "wikidata_claims_missing",
  "wikidata_entities_missing",
  "wikidata_entity_codec_input_invalid",
  "wikidata_entity_id_mismatch",
  "wikidata_entity_missing",
  "wikidata_external_id_literal_invalid",
  "wikidata_identity_mismatch",
  "wikidata_property_not_allowlisted",
  "wikidata_qid_invalid",
  "wikidata_results_missing",
  "wikimedia_api_error",
  "wikimedia_json_invalid",
  "wikimedia_json_object_required",
  "wikipedia_disambiguation_page",
  "wikipedia_extract_control_character",
  "wikipedia_extract_missing",
  "wikipedia_extract_oversized",
  "wikipedia_json_invalid",
  "wikipedia_json_object_required",
  "wikipedia_page_ambiguous",
  "wikipedia_page_identity_invalid",
  "wikipedia_page_missing",
  "wikipedia_pageprops_missing",
  "wikipedia_pages_missing",
  "wikipedia_query_missing",
  "wikipedia_revision_changed",
  "wikipedia_revision_invalid",
  "wikipedia_revision_missing",
  "wikipedia_sitelink_title_invalid",
  "wikipedia_wikidata_identity_mismatch"
]);
export function safeDiagnostic(error: unknown, fallback: string): string {
  try {
    const message = error instanceof Error ? error.message : undefined;
    const code = typeof message === "string" ? message.split(":", 1)[0] : undefined;
    return code && CODES.has(code) ? code : fallback;
  } catch { return fallback; }
}
