"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ProfileAvatar } from "@/components/sidebar-profile-card";
import { RecommendationComposer } from "@/components/social/recommendation-composer";
import { EmptyState } from "@/components/ui/empty-state";
import { LoadingState } from "@/components/ui/loading-state";
import { PageSection } from "@/components/ui/page-section";
import { loadScopedMediaList } from "@/lib/storage";
import { createUserOwnerScope } from "@/lib/local-owner-scope";
import { ACTIVITY_EVENT_TYPES,REACTION_TYPES,mediaToSocialSnapshot,type CursorPage,type ReactionType,type SocialActivity } from "@/lib/social/interactions";
import { markNotificationEntityViewed } from "@/lib/social/notification-sync";
import type { MediaItem } from "@/lib/types";

const ACTIVITY_LABELS:Record<(typeof ACTIVITY_EVENT_TYPES)[number],string>={media_started:"başladı",media_completed:"tamamladı",rating_shared:"puan verdi",favorite_shared:"favorilerine ekledi",shared_note_published:"bir not paylaştı",recommendation_completed:"önerilen medyayı tamamladı",manual_media_share:"medya paylaştı"};
const REACTION_LABELS:Record<ReactionType,string>={like:"Beğen",love:"Sevdim",interesting:"İlginç",celebrate:"Kutla"};

export function ActivityFeed({viewerId}:{viewerId:string}){
  const [items,setItems]=useState<SocialActivity[]>([]);const [nextCursor,setNextCursor]=useState<CursorPage<SocialActivity>["nextCursor"]>();const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [media,setMedia]=useState<MediaItem[]>([]);const [shareKey,setShareKey]=useState("");const [shareText,setShareText]=useState("");const [shareVisibility,setShareVisibility]=useState<"public"|"followers"|"mutual"|"self">("followers");const [recommendTo,setRecommendTo]=useState<string>();
  const load=useCallback(async(append=false,cursor?:CursorPage<SocialActivity>["nextCursor"])=>{await Promise.resolve();setLoading(true);try{const params=new URLSearchParams();if(append&&cursor){params.set("cursorCreatedAt",cursor.createdAt);params.set("cursorId",cursor.id);}const response=await fetch(`/api/social/feed?${params}`,{cache:"no-store"});const data=await response.json() as CursorPage<SocialActivity>&{message?:string};if(!response.ok)throw new Error(data.message??"Akış yüklenemedi.");setItems((current)=>append?[...current,...data.items]:data.items);setNextCursor(data.nextCursor);setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"Akış yüklenemedi.");}finally{setLoading(false);}},[]);
  useEffect(()=>{Promise.resolve().then(()=>{const read=loadScopedMediaList(createUserOwnerScope(viewerId));setMedia(read.status==="valid"||read.status==="empty"?read.data??[]:[]);});const timer=window.setTimeout(()=>void load(false),0);return()=>window.clearTimeout(timer);},[load,viewerId]);
  async function mutate(endpoint:string,body:Record<string,unknown>,method="POST"){const response=await fetch(endpoint,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json() as {message?:string};if(!response.ok)throw new Error(result.message??"Sosyal işlem tamamlanamadı.");}
  async function react(activity:SocialActivity,reaction:ReactionType){try{await mutate("/api/social/reactions",{activityId:activity.id,reaction});await load(false);}catch(error){setMessage(error instanceof Error?error.message:"Tepki kaydedilemedi.");}}
  async function comment(activityId:string,body:string,spoiler:boolean,parentCommentId?:string){try{await mutate("/api/social/comments",{activityId,parentCommentId,body,spoiler,dedupeKey:`comment:${activityId}:${Date.now()}`});await load(false);}catch(error){setMessage(error instanceof Error?error.message:"Yorum gönderilemedi.");}}
  async function share(){const selected=media.find((item)=>mediaToSocialSnapshot(item).canonicalKey===shareKey);if(!selected){setMessage("Paylaşmak için medya seç.");return;}try{const snapshot=mediaToSocialSnapshot(selected);await mutate("/api/social/feed",{action:"publish",eventType:"manual_media_share",visibility:shareVisibility,media:snapshot,text:shareText,sourceEventId:`manual:${selected.id}:${Date.now()}`,dedupeKey:`manual:${snapshot.canonicalKey}:${Date.now()}`});setShareKey("");setShareText("");await load(false);}catch(error){setMessage(error instanceof Error?error.message:"Aktivite paylaşılamadı.");}}
  return <div className="space-y-4"><PageSection title="Manuel medya paylaş" description="Kütüphanendeki bir medyayı görünürlük sınırıyla akışına ekle."><div className="grid gap-2 md:grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)_auto]"><select value={shareKey} onChange={(event)=>setShareKey(event.target.value)} className="app-input rounded-lg border px-3 py-2 text-sm"><option value="">Kütüphaneden seç…</option>{media.map((item)=><option key={item.id} value={mediaToSocialSnapshot(item).canonicalKey}>{item.title}</option>)}</select><select aria-label="Paylaşım görünürlüğü" value={shareVisibility} onChange={(event)=>setShareVisibility(event.target.value as typeof shareVisibility)} className="app-input rounded-lg border px-3 py-2 text-sm"><option value="public">Herkese açık</option><option value="followers">Takipçiler</option><option value="mutual">Karşılıklı</option><option value="self">Yalnızca ben</option></select><input value={shareText} maxLength={500} onChange={(event)=>setShareText(event.target.value)} placeholder="Kısa paylaşım notu (opsiyonel)" className="app-input rounded-lg border px-3 py-2 text-sm"/><button type="button" onClick={()=>void share()} className="app-primary-action rounded-lg px-4 py-2 text-sm font-medium">Paylaş</button></div></PageSection>
    {recommendTo&&<RecommendationComposer userId={viewerId} initialRecipientId={recommendTo} onSent={()=>setRecommendTo(undefined)} onCancel={()=>setRecommendTo(undefined)}/>} {message&&<p role="status" className="rounded-xl border border-[var(--app-border)] bg-[var(--app-panel-bg)] p-3 text-sm text-[var(--app-text-secondary)]">{message}</p>}
    {items.map((activity)=><ActivityCard key={activity.id} activity={activity} viewerId={viewerId} onReact={react} onComment={comment} onRecommend={()=>setRecommendTo(activity.actor.id)} onChanged={()=>load(false)} onMessage={setMessage}/>) }
    {!loading&&items.length===0&&<EmptyState title="Henüz görünür aktivite yok" description="Takip ettiğin kullanıcıların paylaşımları ve görünür medya hareketleri burada yer alacak." />}{loading&&items.length===0&&<LoadingState label="Akış yükleniyor…" rows={4}/>} {loading&&items.length>0&&<LoadingState label="Daha fazla aktivite yükleniyor…" compact rows={1}/>} {nextCursor&&<button type="button" disabled={loading} onClick={()=>void load(true,nextCursor)} className="rounded-lg border border-[var(--app-border-strong)] bg-[var(--app-surface-1)] px-4 py-2 text-sm text-[var(--app-text-secondary)] focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--app-focus)] disabled:text-[var(--app-disabled-text)]">Daha fazla göster</button>}
  </div>;
}

function ActivityCard({activity,viewerId,onReact,onComment,onRecommend,onChanged,onMessage}:{activity:SocialActivity;viewerId:string;onReact:(activity:SocialActivity,reaction:ReactionType)=>Promise<void>;onComment:(activityId:string,body:string,spoiler:boolean,parent?:string)=>Promise<void>;onRecommend:()=>void;onChanged:()=>Promise<void>;onMessage:(value:string)=>void}){
  const [commentOpen,setCommentOpen]=useState(false);const [body,setBody]=useState("");const [spoiler,setSpoiler]=useState(false);const [replyTo,setReplyTo]=useState<string>();const roots=useMemo(()=>activity.comments.filter((comment)=>!comment.parentCommentId),[activity.comments]);
  useEffect(()=>{if(window.location.hash!==`#${activity.id}`)return;const timer=window.setTimeout(()=>setCommentOpen(true),0);void markNotificationEntityViewed("activity",activity.id);return()=>window.clearTimeout(timer);},[activity.id]);
  async function submit(){if(!body.trim())return;await onComment(activity.id,body,spoiler,replyTo);setBody("");setSpoiler(false);setReplyTo(undefined);}
  async function remove(){try{const response=await fetch("/api/social/feed",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete",activityId:activity.id})});if(!response.ok)throw new Error();await onChanged();}catch{onMessage("Aktivite silinemedi.");}}
  async function report(){try{const response=await fetch("/api/social/reports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({activityId:activity.id,category:"other"})});if(!response.ok){const data=await response.json() as {message?:string};throw new Error(data.message);}onMessage("Rapor kaydedildi.");}catch(error){onMessage(error instanceof Error?error.message:"Rapor gönderilemedi.");}}
  async function commentAction(commentId:string,action:"edit"|"delete"|"hide",nextBody?:string,nextSpoiler=false){try{await mutateCommentAction(commentId,action,nextBody,nextSpoiler);await onChanged();}catch(error){onMessage(error instanceof Error?error.message:"Yorum güncellenemedi.");}}
  async function reactComment(commentId:string,reaction:ReactionType){try{const response=await fetch("/api/social/reactions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({commentId,reaction})});const result=await response.json() as {message?:string};if(!response.ok)throw new Error(result.message);await onChanged();}catch(error){onMessage(error instanceof Error?error.message:"Tepki kaydedilemedi.");}}
  async function reportComment(commentId:string){try{const response=await fetch("/api/social/reports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({commentId,category:"other"})});const result=await response.json() as {message?:string};if(!response.ok)throw new Error(result.message);onMessage("Rapor kaydedildi.");}catch(error){onMessage(error instanceof Error?error.message:"Rapor gönderilemedi.");}}
  async function mutateCommentAction(commentId:string,action:string,nextBody?:string,nextSpoiler=false){const response=await fetch("/api/social/comments",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({commentId,action,body:nextBody,spoiler:nextSpoiler})});const result=await response.json() as {message?:string};if(!response.ok)throw new Error(result.message??"Yorum güncellenemedi.");}
  return <article id={activity.id} className="app-card density-card rounded-2xl border transition-colors hover:bg-[var(--app-card-hover)]"><div className="flex items-start gap-3"><ProfileAvatar profileName={activity.actor.displayName} socialAvatarUrl={activity.actor.avatarUrl} allowLocalFallback={false} size="social" shape="circle"/><div className="min-w-0 flex-1"><p className="text-sm"><Link href={activity.actor.username?`/u/${activity.actor.username}`:"/people"} className="font-semibold hover:text-[var(--app-accent-strong)] focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--app-focus)]">{activity.actor.displayName}</Link> <span className="text-[var(--app-text-secondary)]">{ACTIVITY_LABELS[activity.eventType]}</span></p><p className="text-xs text-[var(--app-text-muted)]">{activity.actor.username?`@${activity.actor.username} · `:""}{new Date(activity.createdAt).toLocaleString("tr-TR")} · {activity.visibility}</p></div>{activity.actor.id===viewerId?<button type="button" onClick={()=>void remove()} className="text-xs text-[var(--app-danger)]">Sil</button>:<button type="button" onClick={()=>void report()} className="text-xs text-[var(--app-text-muted)]">Raporla</button>}</div>
    <div className="mt-4 flex gap-3 rounded-xl border border-[var(--app-border)] bg-[var(--app-surface-1)] p-3">{activity.media.coverUrl&&<Image src={activity.media.coverUrl} alt="" width={64} height={96} unoptimized className="h-24 w-16 shrink-0 rounded-md object-cover"/>}<div className="min-w-0"><h2 className="font-semibold">{activity.media.title}</h2><p className="text-xs text-[var(--app-text-muted)]">{activity.media.mediaType} · {activity.media.world}{activity.media.progressSummary?` · ${activity.media.progressSummary}`:""}</p>{activity.rating!==undefined&&<p className="mt-2 text-sm text-[var(--app-warning)]">Puan: {activity.rating}/10</p>}{activity.text&&<p className="mt-2 whitespace-pre-wrap text-sm text-[var(--app-text-secondary)]">{activity.text}</p>}</div></div>
    <div className="mt-3 flex flex-wrap gap-2">{REACTION_TYPES.map((reaction)=><button key={reaction} type="button" aria-pressed={activity.viewerReaction===reaction} onClick={()=>void onReact(activity,reaction)} className={`rounded-full border px-2.5 py-1 text-xs focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--app-focus)] ${activity.viewerReaction===reaction?"border-[var(--app-selected-border)] bg-[var(--app-selected-bg)] text-[var(--app-selected-text)]":"border-[var(--app-border-strong)] text-[var(--app-text-muted)] hover:bg-[var(--app-hover)]"}`}>{REACTION_LABELS[reaction]} {activity.reactions[reaction]??0}</button>)}<button type="button" aria-expanded={commentOpen} onClick={()=>setCommentOpen((value)=>{const next=!value;if(next)void markNotificationEntityViewed("activity",activity.id);return next;})} className="rounded-full border border-[var(--app-border-strong)] px-2.5 py-1 text-xs text-[var(--app-text-muted)]">Yorumlar {activity.commentCount}</button>{activity.actor.id!==viewerId&&<button type="button" onClick={onRecommend} className="rounded-full border border-[var(--app-selected-border)] px-2.5 py-1 text-xs text-[var(--app-accent-strong)]">Medya öner</button>}</div>
    {commentOpen&&<div className="mt-4 border-t border-[var(--app-section-divider)] pt-4"><div className="space-y-3">{roots.map((comment)=><CommentThread key={comment.id} comment={comment} replies={activity.comments.filter((entry)=>entry.parentCommentId===comment.id)} viewerId={viewerId} ownerId={activity.actor.id} onReply={(id)=>{setReplyTo(id);setCommentOpen(true);}} onAction={commentAction} onReact={reactComment} onReport={reportComment}/>)}</div><div className="mt-3"><textarea value={body} onChange={(event)=>setBody(event.target.value)} maxLength={1000} rows={3} placeholder={replyTo?"Cevabını yaz…":"Yorum yaz…"} className="app-input w-full rounded-lg border px-3 py-2 text-sm"/><div className="mt-2 flex flex-wrap items-center gap-3"><label className="text-xs text-[var(--app-text-secondary)]"><input type="checkbox" checked={spoiler} onChange={(event)=>setSpoiler(event.target.checked)} className="mr-2"/>Spoiler</label>{replyTo&&<button type="button" onClick={()=>setReplyTo(undefined)} className="text-xs text-[var(--app-text-muted)]">Cevabı iptal et</button>}<button type="button" onClick={()=>void submit()} className="app-primary-action ml-auto rounded-lg px-3 py-1.5 text-sm">Gönder</button></div></div></div>}
  </article>;
}

function CommentThread({comment,replies,viewerId,ownerId,onReply,onAction,onReact,onReport}:{comment:SocialActivity["comments"][number];replies:SocialActivity["comments"];viewerId:string;ownerId:string;onReply:(id:string)=>void;onAction:(id:string,action:"edit"|"delete"|"hide",body?:string,spoiler?:boolean)=>Promise<void>;onReact:(id:string,reaction:ReactionType)=>Promise<void>;onReport:(id:string)=>Promise<void>}){
  function edit(){const value=window.prompt("Yorumu düzenle",comment.body??"");if(value!==null)void onAction(comment.id,"edit",value,comment.spoiler);}
  const canDelete=viewerId===comment.author.id||viewerId===ownerId;
  return <div className="rounded-lg border border-[var(--app-border)] bg-[var(--app-surface-1)] p-3"><p className="text-xs font-semibold">{comment.author.displayName} <span className="font-normal text-[var(--app-text-muted)]">· {new Date(comment.createdAt).toLocaleString("tr-TR")}</span></p>{comment.deleted?<p className="mt-1 text-sm italic text-[var(--app-text-muted)]">Bu yorum kaldırıldı.</p>:comment.spoiler?<details className="mt-1 text-sm"><summary className="cursor-pointer text-[var(--app-warning)]" aria-label="Spoiler yorumu göster">Spoiler · göstermek için aç</summary><p className="mt-2 whitespace-pre-wrap text-[var(--app-text-secondary)]">{comment.body}</p></details>:<p className="mt-1 whitespace-pre-wrap text-sm text-[var(--app-text-secondary)]">{comment.body}</p>}
    {!comment.deleted&&<div className="mt-2 flex flex-wrap gap-2"><button type="button" onClick={()=>onReply(comment.id)} className="text-xs text-violet-300">Cevapla</button>{REACTION_TYPES.map((reaction)=><button type="button" key={reaction} aria-pressed={comment.viewerReaction===reaction} onClick={()=>void onReact(comment.id,reaction)} className={`text-xs ${comment.viewerReaction===reaction?"text-violet-200":"text-zinc-500"}`}>{REACTION_LABELS[reaction]} {comment.reactions[reaction]??0}</button>)}{viewerId===comment.author.id&&<button type="button" onClick={edit} className="text-xs text-zinc-400">Düzenle</button>}{canDelete&&<button type="button" onClick={()=>void onAction(comment.id,viewerId===ownerId&&viewerId!==comment.author.id?"hide":"delete")} className="text-xs text-rose-300">Kaldır</button>}{!canDelete&&<button type="button" onClick={()=>void onReport(comment.id)} className="text-xs text-zinc-600">Raporla</button>}</div>}
    {replies.length>0&&<div className="ml-3 mt-2 space-y-2 border-l-2 border-[var(--app-border-strong)] pl-3 sm:ml-4">{replies.map((reply)=><CommentThread key={reply.id} comment={reply} replies={[]} viewerId={viewerId} ownerId={ownerId} onReply={()=>onReply(comment.id)} onAction={onAction} onReact={onReact} onReport={onReport}/>)}</div>}</div>;
}
