"use client";

import { Check, ChevronDown, ChevronUp, CircleHelp, Clock3, Flag, Link2, Pause, Play, RotateCcw, X } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { RecommendationComposer } from "@/components/social/recommendation-composer";
import { RecommendationDetail } from "@/components/social/recommendation-detail";
import { EmptyState } from "@/components/ui/empty-state";
import { ErrorState } from "@/components/ui/error-state";
import { FilterToolbar } from "@/components/ui/filter-toolbar";
import { LoadingState } from "@/components/ui/loading-state";
import { SegmentedTabs } from "@/components/ui/segmented-tabs";
import { StatusBadge as SharedStatusBadge, type StatusBadgeTone } from "@/components/ui/status-badge";
import { loadMediaList, saveMediaList } from "@/lib/storage";
import { isRecommendationTransitionAllowed, type CursorPage, type SocialRecommendation } from "@/lib/social/interactions";
import { findMatchingLocalMedia, recommendationToPlanningMedia, saveRecommendationLink, validRecommendationLinkIds } from "@/lib/social/local-social";
import { markNotificationEntityViewed } from "@/lib/social/notification-sync";
import { recommendationCardMode, recommendationProgressPresentation, recommendationResponsePresentation, type StatusPresentation } from "@/lib/social/recommendation-presentation";

const FILTERS = ["all", "pending", "deferred", "accepted", "started", "completed", "rejected", "withdrawn"] as const;
const FILTER_LABELS: Record<(typeof FILTERS)[number], string> = { all: "Tümü", pending: "Yanıt bekliyor", deferred: "Sonraya bırakıldı", accepted: "Kabul edildi", started: "Başlandı", completed: "Tamamlandı", rejected: "Reddedildi", withdrawn: "Geri çekildi" };
const ICONS = { clock: Clock3, pause: Pause, check: Check, x: X, undo: RotateCcw, link: Link2, play: Play, flag: Flag, help: CircleHelp };
const BADGE_TONES: Record<StatusPresentation["tone"], StatusBadgeTone> = { amber: "warning", sky: "info", emerald: "success", rose: "danger", zinc: "neutral", violet: "accent" };

function StatusBadge({ presentation }: { presentation: StatusPresentation }) { const Icon = ICONS[presentation.icon]; return <SharedStatusBadge label={presentation.label} tone={BADGE_TONES[presentation.tone]} icon={<Icon aria-hidden="true" className="h-3.5 w-3.5"/>}>{presentation.label}</SharedStatusBadge>; }

export function RecommendationInbox({ userId, initialRecipientId, composeInitially = false }: { userId: string; initialRecipientId?: string; composeInitially?: boolean }) {
  const [box, setBox] = useState<"received" | "sent">("received"); const [filter, setFilter] = useState<(typeof FILTERS)[number]>("all"); const [items, setItems] = useState<SocialRecommendation[]>([]); const [nextCursor, setNextCursor] = useState<CursorPage<SocialRecommendation>["nextCursor"]>(); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [message, setMessage] = useState(""); const [compose, setCompose] = useState(composeInitially || Boolean(initialRecipientId)); const [linkedIds, setLinkedIds] = useState<Set<string>>(() => new Set());
  const load = useCallback(async (append = false, cursor?: CursorPage<SocialRecommendation>["nextCursor"]) => { await Promise.resolve(); setLoading(true); try { const params = new URLSearchParams({ box, status: filter }); if (append && cursor) { params.set("cursorCreatedAt", cursor.createdAt); params.set("cursorId", cursor.id); } const response = await fetch(`/api/social/recommendations?${params}`, { cache: "no-store" }); const data = await response.json() as CursorPage<SocialRecommendation> & { message?: string }; if (!response.ok) throw new Error(data.message ?? "Öneriler yüklenemedi."); setItems((current) => append ? [...current, ...data.items] : data.items); setNextCursor(data.nextCursor); setLoadError(""); } catch (error) { setLoadError(error instanceof Error ? error.message : "Öneriler yüklenemedi."); } finally { setLoading(false); } }, [box, filter]);
  useEffect(() => { const timer = window.setTimeout(() => void load(false), 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { const timer = window.setTimeout(() => setLinkedIds(new Set(validRecommendationLinkIds(userId, loadMediaList() ?? []))), 0); return () => window.clearTimeout(timer); }, [userId]);
  function rememberLink(item: SocialRecommendation, localMediaId: string) { saveRecommendationLink({ recommendationId: item.id, localMediaId, canonicalMediaKey: item.canonicalMediaKey, linkedAt: new Date().toISOString(), userId }); setLinkedIds((current) => new Set(current).add(item.id)); }
  async function transition(item: SocialRecommendation, action: "accept" | "defer" | "reject" | "withdraw" | "linked", alreadyInLibrary = false, responseMessage?: string) { try { const response = await fetch("/api/social/recommendations", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recommendationId: item.id, action, responseStatus: item.responseStatus, progressStatus: item.progressStatus, dedupeKey: `${action}:${item.id}`, alreadyInLibrary, responseMessage }) }); const result = await response.json() as { message?: string }; if (!response.ok) throw new Error(result.message ?? "Öneri güncellenemedi."); if (action === "accept") { const existing = findMatchingLocalMedia(item.media, loadMediaList() ?? []); if (existing) { rememberLink(item, existing.id); await transition({ ...item, responseStatus: "accepted" }, "linked", true); setMessage("Öneri kabul edildi ve mevcut kütüphane kaydına bağlandı."); return; } } await load(false); } catch (error) { setMessage(error instanceof Error ? error.message : "Öneri güncellenemedi."); } }
  async function addToLibrary(item: SocialRecommendation) { try { const current = loadMediaList() ?? []; const existing = findMatchingLocalMedia(item.media, current); const local = existing ?? recommendationToPlanningMedia(item.id, item.media); if (!existing) saveMediaList([...current, local]); rememberLink(item, local.id); if (item.progressStatus === "none") await transition(item, "linked", Boolean(existing)); setMessage(existing ? "Öneri mevcut medya kaydına bağlandı." : "Medya planlanan olarak bu cihazdaki kütüphaneye eklendi."); } catch (error) { setMessage(error instanceof Error ? error.message : "Kütüphane bağlantısı kurulamadı; öneri kabulü korunuyor."); } }
  return <div className="space-y-4"><FilterToolbar filters={<div className="flex min-w-max gap-3"><SegmentedTabs label="Öneri kutusu" value={box} onValueChange={setBox} options={[{value:"received",label:"Gelenler"},{value:"sent",label:"Gönderilenler"}]}/><SegmentedTabs label="Öneri durumları" compact value={filter} onValueChange={setFilter} options={FILTERS.map((value)=>({value,label:FILTER_LABELS[value]}))}/></div>} actions={<button type="button" aria-expanded={compose} onClick={() => setCompose((value) => !value)} className="app-primary-action rounded-lg px-3 py-2 text-sm font-medium">Medya öner</button>}/>
    {compose && <RecommendationComposer initialRecipientId={initialRecipientId} onCancel={() => setCompose(false)} onSent={() => { setCompose(false); setBox("sent"); void load(false); }}/>} {message && <p role="status" className="rounded-xl border border-[var(--app-border)] bg-[var(--app-panel-bg)] p-3 text-sm text-[var(--app-text-secondary)]">{message}</p>} {loadError && <ErrorState compact title="Öneriler yüklenemedi" description={loadError} retryLabel="Tekrar dene" onRetry={() => void load(false)}/>}
    <div className="grid gap-3">{items.map((item) => <RecommendationCard key={item.id} item={item} box={box} locallyLinked={linkedIds.has(item.id)} onAction={(action, responseMessage) => transition(item, action, false, responseMessage)} onAdd={() => addToLibrary(item)} onChanged={() => load(false)}/>)}</div>{!loading && !loadError && items.length === 0 && <EmptyState title="Bu görünümde öneri yok" description="Filtreyi değiştirebilir veya bir kullanıcıya yeni medya önerisi gönderebilirsin." primaryAction={<button type="button" onClick={()=>setCompose(true)} className="app-primary-action rounded-lg px-3 py-2 text-sm">Medya öner</button>}/>} {loading&&items.length===0&&<LoadingState label="Öneriler yükleniyor…" rows={3}/>} {nextCursor && <button type="button" onClick={() => void load(true, nextCursor)} className="rounded-lg border border-[var(--app-border-strong)] bg-[var(--app-surface-1)] px-4 py-2 text-sm text-[var(--app-text-secondary)]">Daha fazla göster</button>}</div>;
}

function RecommendationCard({ item, box, locallyLinked, onAction, onAdd, onChanged }: { item: SocialRecommendation; box: "received" | "sent"; locallyLinked: boolean; onAction: (action: "accept" | "defer" | "reject" | "withdraw" | "linked", responseMessage?: string) => Promise<void>; onAdd: () => Promise<void>; onChanged: () => Promise<void> }) {
  const [expanded, setExpanded] = useState(false); const [responseMessage, setResponseMessage] = useState("");
  const actions = useMemo(() => ({ accept: isRecommendationTransitionAllowed(item.responseStatus, item.progressStatus, "accept"), defer: isRecommendationTransitionAllowed(item.responseStatus, item.progressStatus, "defer"), reject: isRecommendationTransitionAllowed(item.responseStatus, item.progressStatus, "reject"), withdraw: isRecommendationTransitionAllowed(item.responseStatus, item.progressStatus, "withdraw") }), [item]);
  const mode = recommendationCardMode(item.responseStatus); const response = recommendationResponsePresentation(item.responseStatus); const progress = recommendationProgressPresentation(item.progressStatus);
  useEffect(() => { if (window.location.hash !== `#${item.id}`) return; const timer = window.setTimeout(() => setExpanded(true), 0); void markNotificationEntityViewed("recommendation", item.id); return () => window.clearTimeout(timer); }, [item.id]);
  function toggle() { setExpanded((value) => { const next = !value; if (next) void markNotificationEntityViewed("recommendation", item.id); return next; }); }
  const muted = item.responseStatus === "rejected" || item.responseStatus === "withdrawn";
  return <article id={item.id} className={`app-card rounded-2xl border p-4 ${muted ? "border-dashed" : ""}`}><div className="flex flex-col gap-4 sm:flex-row"><div className="flex min-w-0 flex-1 gap-3">{item.media.coverUrl && <Image src={item.media.coverUrl} alt="" width={mode === "compact" ? 56 : 72} height={mode === "compact" ? 84 : 108} unoptimized className={`${mode === "compact" ? "h-20 w-14" : "h-28 w-[72px]"} shrink-0 rounded-lg object-cover`}/>}<div className="min-w-0"><h2 className="font-semibold">{item.media.title}</h2><p className="mt-1 text-xs text-[var(--app-text-muted)]">{box === "received" ? "Gönderen" : "Alıcı"}: {item.other.username?<Link href={`/u/${item.other.username}`} className="font-medium text-[var(--app-accent-strong)] hover:underline">{item.other.displayName} · @{item.other.username}</Link>:item.other.displayName}</p><div className="mt-2 flex flex-wrap gap-2"><StatusBadge presentation={response}/><StatusBadge presentation={progress}/>{item.alreadyInLibrary && <SharedStatusBadge>Zaten kütüphanendeydi</SharedStatusBadge>}</div>{mode !== "compact" && item.senderNote && <p className="mt-2 whitespace-pre-wrap text-sm text-[var(--app-text-secondary)]">“{item.senderNote}”</p>}{item.lastMessagePreview?.body && <p className="mt-2 line-clamp-1 text-sm text-[var(--app-text-muted)]">Son geri bildirim: {item.lastMessagePreview.body}</p>}<p className="mt-2 text-xs text-[var(--app-text-muted)]">{new Date(item.updatedAt ?? item.createdAt).toLocaleString("tr-TR")}</p></div></div>
      <div className="flex shrink-0 flex-wrap content-start gap-2 sm:max-w-56">{box === "received" && actions.accept && <button type="button" onClick={() => void onAction("accept", responseMessage)} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs">Kabul et</button>}{box === "received" && actions.defer && <button type="button" onClick={() => void onAction("defer", responseMessage)} className="rounded-lg bg-sky-900 px-3 py-2 text-xs text-sky-200">Sonraya bırak</button>}{box === "received" && actions.reject && <button type="button" onClick={() => void onAction("reject", responseMessage)} className="rounded-lg bg-rose-950 px-3 py-2 text-xs text-rose-200">Reddet</button>}{box === "sent" && actions.withdraw && <button type="button" onClick={() => void onAction("withdraw")} className="rounded-lg bg-zinc-700 px-3 py-2 text-xs">Geri çek</button>}{box === "received" && item.responseStatus === "accepted" && !locallyLinked && <button type="button" onClick={() => void onAdd()} className="rounded-lg bg-violet-600 px-3 py-2 text-xs">{item.progressStatus === "none" ? "Kütüphaneye ekle" : "Kütüphaneye bağla"}</button>}<button type="button" onClick={toggle} aria-expanded={expanded} className="inline-flex items-center gap-1 rounded-lg border border-zinc-700 px-3 py-2 text-xs">{expanded ? <ChevronUp aria-hidden="true" className="h-3.5 w-3.5"/> : <ChevronDown aria-hidden="true" className="h-3.5 w-3.5"/>}{expanded ? "Detayları kapat" : item.progressStatus === "started" || item.progressStatus === "completed" ? "Geri bildirim yaz" : "Detayları aç"}</button></div></div>
    {box === "received" && (mode === "full" || mode === "medium") && <label className="mt-3 block text-xs text-[var(--app-text-secondary)]">Yanıtına geri bildirim ekle (opsiyonel)<textarea value={responseMessage} onChange={(event) => setResponseMessage(event.target.value)} maxLength={500} rows={2} className="app-input mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label>}{expanded && <RecommendationDetail recommendationId={item.id} onChanged={onChanged}/>}</article>;
}
