"use client";

import { Check, ChevronDown, ChevronUp, CircleHelp, Clock3, Flag, Link2, Pause, Play, RotateCcw, X } from "lucide-react";
import Image from "next/image";
import { useCallback, useEffect, useMemo, useState } from "react";
import { RecommendationComposer } from "@/components/social/recommendation-composer";
import { RecommendationDetail } from "@/components/social/recommendation-detail";
import { loadMediaList, saveMediaList } from "@/lib/storage";
import { isRecommendationTransitionAllowed, type CursorPage, type SocialRecommendation } from "@/lib/social/interactions";
import { findMatchingLocalMedia, recommendationToPlanningMedia, saveRecommendationLink, validRecommendationLinkIds } from "@/lib/social/local-social";
import { markNotificationEntityViewed } from "@/lib/social/notification-sync";
import { recommendationCardMode, recommendationProgressPresentation, recommendationResponsePresentation, type StatusPresentation } from "@/lib/social/recommendation-presentation";

const FILTERS = ["all", "pending", "deferred", "accepted", "started", "completed", "rejected", "withdrawn"] as const;
const FILTER_LABELS: Record<(typeof FILTERS)[number], string> = { all: "Tümü", pending: "Yanıt bekliyor", deferred: "Sonraya bırakıldı", accepted: "Kabul edildi", started: "Başlandı", completed: "Tamamlandı", rejected: "Reddedildi", withdrawn: "Geri çekildi" };
const TONE_CLASSES: Record<StatusPresentation["tone"], string> = { amber: "border-amber-500/30 bg-amber-500/10 text-amber-200", sky: "border-sky-500/30 bg-sky-500/10 text-sky-200", emerald: "border-emerald-500/30 bg-emerald-500/10 text-emerald-200", rose: "border-rose-500/30 bg-rose-500/10 text-rose-200", zinc: "border-zinc-700 bg-zinc-800 text-zinc-300", violet: "border-violet-500/30 bg-violet-500/10 text-violet-200" };
const ICONS = { clock: Clock3, pause: Pause, check: Check, x: X, undo: RotateCcw, link: Link2, play: Play, flag: Flag, help: CircleHelp };

function StatusBadge({ presentation }: { presentation: StatusPresentation }) { const Icon = ICONS[presentation.icon]; return <span aria-label={presentation.label} className={`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-xs ${TONE_CLASSES[presentation.tone]}`}><Icon aria-hidden="true" className="h-3.5 w-3.5"/>{presentation.label}</span>; }

export function RecommendationInbox({ userId, initialRecipientId, composeInitially = false }: { userId: string; initialRecipientId?: string; composeInitially?: boolean }) {
  const [box, setBox] = useState<"received" | "sent">("received"); const [filter, setFilter] = useState<(typeof FILTERS)[number]>("all"); const [items, setItems] = useState<SocialRecommendation[]>([]); const [nextCursor, setNextCursor] = useState<CursorPage<SocialRecommendation>["nextCursor"]>(); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [message, setMessage] = useState(""); const [compose, setCompose] = useState(composeInitially || Boolean(initialRecipientId)); const [linkedIds, setLinkedIds] = useState<Set<string>>(() => new Set());
  const load = useCallback(async (append = false, cursor?: CursorPage<SocialRecommendation>["nextCursor"]) => { await Promise.resolve(); setLoading(true); try { const params = new URLSearchParams({ box, status: filter }); if (append && cursor) { params.set("cursorCreatedAt", cursor.createdAt); params.set("cursorId", cursor.id); } const response = await fetch(`/api/social/recommendations?${params}`, { cache: "no-store" }); const data = await response.json() as CursorPage<SocialRecommendation> & { message?: string }; if (!response.ok) throw new Error(data.message ?? "Öneriler yüklenemedi."); setItems((current) => append ? [...current, ...data.items] : data.items); setNextCursor(data.nextCursor); setLoadError(""); } catch (error) { setLoadError(error instanceof Error ? error.message : "Öneriler yüklenemedi."); } finally { setLoading(false); } }, [box, filter]);
  useEffect(() => { const timer = window.setTimeout(() => void load(false), 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { const timer = window.setTimeout(() => setLinkedIds(new Set(validRecommendationLinkIds(userId, loadMediaList() ?? []))), 0); return () => window.clearTimeout(timer); }, [userId]);
  function rememberLink(item: SocialRecommendation, localMediaId: string) { saveRecommendationLink({ recommendationId: item.id, localMediaId, canonicalMediaKey: item.canonicalMediaKey, linkedAt: new Date().toISOString(), userId }); setLinkedIds((current) => new Set(current).add(item.id)); }
  async function transition(item: SocialRecommendation, action: "accept" | "defer" | "reject" | "withdraw" | "linked", alreadyInLibrary = false, responseMessage?: string) { try { const response = await fetch("/api/social/recommendations", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recommendationId: item.id, action, responseStatus: item.responseStatus, progressStatus: item.progressStatus, dedupeKey: `${action}:${item.id}`, alreadyInLibrary, responseMessage }) }); const result = await response.json() as { message?: string }; if (!response.ok) throw new Error(result.message ?? "Öneri güncellenemedi."); if (action === "accept") { const existing = findMatchingLocalMedia(item.media, loadMediaList() ?? []); if (existing) { rememberLink(item, existing.id); await transition({ ...item, responseStatus: "accepted" }, "linked", true); setMessage("Öneri kabul edildi ve mevcut kütüphane kaydına bağlandı."); return; } } await load(false); } catch (error) { setMessage(error instanceof Error ? error.message : "Öneri güncellenemedi."); } }
  async function addToLibrary(item: SocialRecommendation) { try { const current = loadMediaList() ?? []; const existing = findMatchingLocalMedia(item.media, current); const local = existing ?? recommendationToPlanningMedia(item.id, item.media); if (!existing) saveMediaList([...current, local]); rememberLink(item, local.id); if (item.progressStatus === "none") await transition(item, "linked", Boolean(existing)); setMessage(existing ? "Öneri mevcut medya kaydına bağlandı." : "Medya planlanan olarak bu cihazdaki kütüphaneye eklendi."); } catch (error) { setMessage(error instanceof Error ? error.message : "Kütüphane bağlantısı kurulamadı; öneri kabulü korunuyor."); } }
  return <div className="space-y-4"><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={() => setBox("received")} className={`rounded-lg px-3 py-2 text-sm ${box === "received" ? "bg-violet-600" : "bg-zinc-900"}`}>Gelenler</button><button type="button" onClick={() => setBox("sent")} className={`rounded-lg px-3 py-2 text-sm ${box === "sent" ? "bg-violet-600" : "bg-zinc-900"}`}>Gönderilenler</button><button type="button" onClick={() => setCompose((value) => !value)} className="ml-auto rounded-lg border border-violet-500/40 px-3 py-2 text-sm text-violet-200">Medya öner</button></div>
    {compose && <RecommendationComposer initialRecipientId={initialRecipientId} onCancel={() => setCompose(false)} onSent={() => { setCompose(false); setBox("sent"); void load(false); }}/>}<div className="flex gap-2 overflow-x-auto pb-1">{FILTERS.map((value) => <button key={value} type="button" onClick={() => setFilter(value)} className={`shrink-0 rounded-full border px-3 py-1 text-xs ${filter === value ? "border-violet-400 text-violet-200" : "border-zinc-700 text-zinc-400"}`}>{FILTER_LABELS[value]}</button>)}</div>{message && <p role="status" className="rounded-lg bg-zinc-900 p-3 text-sm text-zinc-400">{message}</p>}{loadError && <div role="alert" className="flex items-center justify-between gap-3 rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-200"><span>{loadError}</span><button type="button" onClick={() => void load(false)} className="shrink-0 rounded-lg border border-rose-400/40 px-3 py-1.5">Tekrar dene</button></div>}
    <div className="grid gap-3">{items.map((item) => <RecommendationCard key={item.id} item={item} box={box} locallyLinked={linkedIds.has(item.id)} onAction={(action, responseMessage) => transition(item, action, false, responseMessage)} onAdd={() => addToLibrary(item)} onChanged={() => load(false)}/>)}</div>{!loading && !loadError && items.length === 0 && <div className="rounded-2xl border border-dashed border-zinc-800 p-8 text-center text-zinc-500">Bu filtrede öneri yok.</div>}{loading && <p className="text-sm text-zinc-500">Öneriler yükleniyor…</p>}{nextCursor && <button type="button" onClick={() => void load(true, nextCursor)} className="rounded-lg border border-zinc-700 px-4 py-2 text-sm">Daha fazla göster</button>}</div>;
}

function RecommendationCard({ item, box, locallyLinked, onAction, onAdd, onChanged }: { item: SocialRecommendation; box: "received" | "sent"; locallyLinked: boolean; onAction: (action: "accept" | "defer" | "reject" | "withdraw" | "linked", responseMessage?: string) => Promise<void>; onAdd: () => Promise<void>; onChanged: () => Promise<void> }) {
  const [expanded, setExpanded] = useState(false); const [responseMessage, setResponseMessage] = useState("");
  const actions = useMemo(() => ({ accept: isRecommendationTransitionAllowed(item.responseStatus, item.progressStatus, "accept"), defer: isRecommendationTransitionAllowed(item.responseStatus, item.progressStatus, "defer"), reject: isRecommendationTransitionAllowed(item.responseStatus, item.progressStatus, "reject"), withdraw: isRecommendationTransitionAllowed(item.responseStatus, item.progressStatus, "withdraw") }), [item]);
  const mode = recommendationCardMode(item.responseStatus); const response = recommendationResponsePresentation(item.responseStatus); const progress = recommendationProgressPresentation(item.progressStatus);
  useEffect(() => { if (window.location.hash !== `#${item.id}`) return; const timer = window.setTimeout(() => setExpanded(true), 0); void markNotificationEntityViewed("recommendation", item.id); return () => window.clearTimeout(timer); }, [item.id]);
  function toggle() { setExpanded((value) => { const next = !value; if (next) void markNotificationEntityViewed("recommendation", item.id); return next; }); }
  const muted = item.responseStatus === "rejected" || item.responseStatus === "withdrawn";
  return <article id={item.id} className={`rounded-2xl border border-zinc-800 bg-zinc-900/70 p-4 ${muted ? "opacity-80" : ""}`}><div className="flex flex-col gap-4 sm:flex-row"><div className="flex min-w-0 flex-1 gap-3">{item.media.coverUrl && <Image src={item.media.coverUrl} alt="" width={mode === "compact" ? 56 : 72} height={mode === "compact" ? 84 : 108} unoptimized className={`${mode === "compact" ? "h-20 w-14" : "h-28 w-[72px]"} shrink-0 rounded-lg object-cover`}/>}<div className="min-w-0"><h2 className="font-semibold">{item.media.title}</h2><p className="mt-1 text-xs text-zinc-500">{box === "received" ? "Gönderen" : "Alıcı"}: {item.other.displayName}{item.other.username ? ` · @${item.other.username}` : ""}</p><div className="mt-2 flex flex-wrap gap-2"><StatusBadge presentation={response}/><StatusBadge presentation={progress}/>{item.alreadyInLibrary && <span className="rounded-full border border-zinc-700 px-2 py-1 text-xs text-zinc-300">Zaten kütüphanendeydi</span>}</div>{mode !== "compact" && item.senderNote && <p className="mt-2 whitespace-pre-wrap text-sm text-zinc-300">“{item.senderNote}”</p>}{item.lastMessagePreview?.body && <p className="mt-2 line-clamp-1 text-sm text-zinc-400">Son geri bildirim: {item.lastMessagePreview.body}</p>}<p className="mt-2 text-xs text-zinc-600">{new Date(item.updatedAt ?? item.createdAt).toLocaleString("tr-TR")}</p></div></div>
      <div className="flex shrink-0 flex-wrap content-start gap-2 sm:max-w-56">{box === "received" && actions.accept && <button type="button" onClick={() => void onAction("accept", responseMessage)} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs">Kabul et</button>}{box === "received" && actions.defer && <button type="button" onClick={() => void onAction("defer", responseMessage)} className="rounded-lg bg-sky-900 px-3 py-2 text-xs text-sky-200">Sonraya bırak</button>}{box === "received" && actions.reject && <button type="button" onClick={() => void onAction("reject", responseMessage)} className="rounded-lg bg-rose-950 px-3 py-2 text-xs text-rose-200">Reddet</button>}{box === "sent" && actions.withdraw && <button type="button" onClick={() => void onAction("withdraw")} className="rounded-lg bg-zinc-700 px-3 py-2 text-xs">Geri çek</button>}{box === "received" && item.responseStatus === "accepted" && !locallyLinked && <button type="button" onClick={() => void onAdd()} className="rounded-lg bg-violet-600 px-3 py-2 text-xs">{item.progressStatus === "none" ? "Kütüphaneye ekle" : "Kütüphaneye bağla"}</button>}<button type="button" onClick={toggle} aria-expanded={expanded} className="inline-flex items-center gap-1 rounded-lg border border-zinc-700 px-3 py-2 text-xs">{expanded ? <ChevronUp aria-hidden="true" className="h-3.5 w-3.5"/> : <ChevronDown aria-hidden="true" className="h-3.5 w-3.5"/>}{expanded ? "Detayları kapat" : item.progressStatus === "started" || item.progressStatus === "completed" ? "Geri bildirim yaz" : "Detayları aç"}</button></div></div>
    {box === "received" && (mode === "full" || mode === "medium") && <label className="mt-3 block text-xs text-zinc-400">Yanıtına geri bildirim ekle (opsiyonel)<textarea value={responseMessage} onChange={(event) => setResponseMessage(event.target.value)} maxLength={500} rows={2} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm"/></label>}{expanded && <RecommendationDetail recommendationId={item.id} onChanged={onChanged}/>}</article>;
}
