"use client";

import { useEffect, useState } from "react";
import { cacheSocialActivityPreferences } from "@/lib/social/local-social";
import { DEFAULT_ACTIVITY_PREFERENCES,DEFAULT_NOTIFICATION_PREFERENCES,RECOMMENDATION_PERMISSIONS,type ActivityPreferences,type NotificationPreferences,type RecommendationPermission,type SocialPreferences } from "@/lib/social/interactions";

export function SocialPreferencesPanel({userId}:{userId:string}){
  const [activity,setActivity]=useState<ActivityPreferences>(DEFAULT_ACTIVITY_PREFERENCES);const [notifications,setNotifications]=useState<NotificationPreferences>(DEFAULT_NOTIFICATION_PREFERENCES);const [permission,setPermission]=useState<RecommendationPermission>("mutual");const [message,setMessage]=useState("");
  useEffect(()=>{fetch("/api/social/preferences",{cache:"no-store"}).then((response)=>response.json() as Promise<SocialPreferences>).then((data)=>{setActivity(data.activity);setNotifications(data.notifications);setPermission(data.recommendationPermission);cacheSocialActivityPreferences(userId,data.configured,data.activity);}).catch(()=>setMessage("Sosyal tercihler yüklenemedi."));},[userId]);
  async function save(kind:"activity"|"notifications"|"recommendations",values:unknown){const response=await fetch("/api/social/preferences",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,values})});const result=await response.json() as SocialPreferences&{message?:string};if(!response.ok)throw new Error(result.message??"Tercihler kaydedilemedi.");setMessage("Sosyal tercihler kaydedildi.");if(kind==="activity")cacheSocialActivityPreferences(userId,result.configured,result.activity);}
  const toggleActivity=(key:keyof Omit<ActivityPreferences,"defaultVisibility">)=><label className="flex items-center gap-2 text-sm text-zinc-300"><input type="checkbox" checked={activity[key]} onChange={(event)=>setActivity((value)=>({...value,[key]:event.target.checked}))}/>{({shareCompleted:"Tamamlamaları otomatik paylaş",shareStarted:"Başlamaları otomatik paylaş",shareRating:"Puanları otomatik paylaş",shareFavorite:"Favorileri otomatik paylaş",shareRecommendationCompleted:"Tamamlanan arkadaş önerilerini paylaş"} as const)[key]}</label>;
  const toggleNotification=(key:keyof NotificationPreferences,label:string)=><label className="flex items-center gap-2 text-sm text-zinc-300"><input type="checkbox" checked={notifications[key]} onChange={(event)=>setNotifications((value)=>({...value,[key]:event.target.checked}))}/>{label}</label>;
  return <details className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-4"><summary className="cursor-pointer font-semibold">Sosyal paylaşım ve bildirim tercihleri</summary><div className="mt-4 grid gap-5 lg:grid-cols-3"><section className="space-y-2"><h3 className="text-sm font-semibold text-zinc-200">Aktivite paylaşımı</h3>{toggleActivity("shareCompleted")}{toggleActivity("shareStarted")}{toggleActivity("shareRating")}{toggleActivity("shareFavorite")}{toggleActivity("shareRecommendationCompleted")}<label className="block text-xs text-zinc-400">Varsayılan görünürlük<select value={activity.defaultVisibility} onChange={(event)=>setActivity((value)=>({...value,defaultVisibility:event.target.value as ActivityPreferences["defaultVisibility"]}))} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-2 py-2 text-sm">{["public","followers","mutual","self"].map((value)=><option key={value}>{value}</option>)}</select></label><button onClick={()=>void save("activity",activity).catch((error)=>setMessage(error.message))} className="rounded-lg bg-violet-600 px-3 py-2 text-sm">Kaydet</button></section>
    <section className="space-y-2"><h3 className="text-sm font-semibold text-zinc-200">Öneri izni</h3><select value={permission} onChange={(event)=>setPermission(event.target.value as RecommendationPermission)} className="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-2 py-2 text-sm">{RECOMMENDATION_PERMISSIONS.map((value)=><option key={value}>{value}</option>)}</select><p className="text-xs text-zinc-500">Personal profiller öneri almaz; block her seçeneğin üzerindedir.</p><button onClick={()=>void save("recommendations",{permission}).catch((error)=>setMessage(error.message))} className="rounded-lg bg-violet-600 px-3 py-2 text-sm">Kaydet</button></section>
    <section className="space-y-2"><h3 className="text-sm font-semibold text-zinc-200">Bildirimler</h3>{toggleNotification("follow","Takip bildirimleri")}{toggleNotification("comments","Yorum ve cevaplar")}{toggleNotification("reactions","Tepkiler")}{toggleNotification("recommendationReceived","Yeni öneri")}{toggleNotification("recommendationAccepted","Kabul ve erteleme")}{toggleNotification("recommendationStarted","Öneriye başlanması")}{toggleNotification("recommendationCompleted","Önerinin tamamlanması")}{toggleNotification("recommendationRejected","Önerinin reddedilmesi")}{toggleNotification("recommendationWithdrawn","Önerinin geri çekilmesi")}<button onClick={()=>void save("notifications",notifications).catch((error)=>setMessage(error.message))} className="rounded-lg bg-violet-600 px-3 py-2 text-sm">Kaydet</button></section></div>{message&&<p role="status" className="mt-3 text-sm text-zinc-400">{message}</p>}</details>;
}
